src/index.ts

This is way harder than it should be.
Duplicating the logic on the existing `help` it's not ideal, but [vorpal](https://github.com/dthree/vorpal) doesn't really help. I tried to leave a compelling comment on the code

New help command order #7

---

src/commands/init.ts

remove unnecessary empty defaults

---

package.json
pages/linker.js
src/utils/linker.ts

- Upgraded decentraland-commons
- Dropped decentraland-contracts
you will need an `npm update` in order for this to work

[chore] Upgrade decentraland-commons

---

src/commands/init.ts
src/commands/upgrade.ts
src/utils/get-root.ts
src/utils/is-outdated.ts
src/utils/linker-checker.ts
src/utils/linker.ts
src/utils/serve.ts
src/utils/uploader.ts

use a function to compute the root path

[chore] path dry

---

package.json

chore: update commons

---

src/commands/init.ts
src/commands/upgrade.ts
src/utils/is-outdated.ts
src/utils/linker-checker.ts
src/utils/linker.ts
src/utils/uploader.ts

Improves cross-platform compatibility.

Feature: use path module for path names

---

package.json

- Change `postinstall` to `prepublish`

:bug: postintall crash at install

---

.dclignore
.gitignore
dev.js
package.json
pages/linker.js
src/commands/init.ts
src/creation/init.ts
src/utils/get-root.ts
src/utils/is-dev.ts
src/utils/uploader.ts

- Add `.decentralandignore` at the `root`
- Upload all the files inside the `root` folder if they are not ignored in `.dclignore`
- Check if the main file in `scene.json` is a supported format
Fix #95

Load files based on .dclignore & check main format

---

test/lib/project.spec.ts

Added tests to ensure that the .dclignore file is processed correctly
Closes CLIENT-53

test: .dclignore

---

src/commands/preview.ts
src/utils/moduleHelpers.ts
test/integration/init.spec.ts

Fixes a bug where the preview won't work when watching for file changes.

fix: preview should run in watch mode

---

package-lock.json
package.json
src/lib/Ethereum.ts
src/lib/Project.ts
test/integration/decentraland.spec.ts
test/integration/project.spec.ts
test/integration/sandbox.ts
test/lib/project.spec.ts

Fixed and tested getFiles and getAllFilePaths.
The issue was that we weren't uploading nested folders, that was due to several small issues which are fixed with this pr.

fix: getFiles and getAllFilePaths

---

package-lock.json
src/lib/IPFS.ts

Close [CLIENT-92](https://decentraland.atlassian.net/browse/CLIENT-92)

chore: enhance ipfs error message

---

scripts/npmPublish.ts

We can't guarantee that it's a pre-release, skip check if it's not the case

fix: npm publish script

---

npm-shrinkwrap.json
package.json
src/lib/Decentraland.ts
src/lib/Preview.ts
src/lib/Project.ts

Closes [CLIENT-45](https://decentraland.atlassian.net/browse/CLIENT-45)

feat: live reload

---

npm-shrinkwrap.json
package.json
src/commands/init.ts
src/commands/link.ts
src/commands/pin.ts
src/commands/preview.ts
src/index.ts
src/lib/Project.ts
src/utils/analytics.ts
src/utils/dclinfo.ts
src/utils/filesystem.ts

closes [CLIENT-52](https://decentraland.atlassian.net/browse/CLIENT-52)
Uhh in this one I did some extra housekeeping, sorry for the noise

chore: added pre commit hooks

---

.circleci/config.yml
package-lock.json
package.json
scripts/unlockDevDeps.ts

Closes [CLIENT-106](https://decentraland.atlassian.net/browse/CLIENT-106)

fix: prevent devdependencies from being installed

---

src/lib/Decentraland.ts
src/lib/Ethereum.ts
src/lib/Project.ts
src/utils/coordinateHelpers.ts
test/unit/lib/decentraland.spec.ts
test/unit/utils/coordinateHelpers.spec.ts

scene.json:
```json
{
"scene": {
"parcels": ["-1000,100"],
"base": "-1000,100"
}
}
```
scene.json:
```json
{
"scene": {
"parcels": ["-10,100"],
"base": "-53,47"
}
}
```
scene.json:
```json
{
"scene": {
"parcels": ["0,0", "-100,100", "15,-15", "-40,40"],
"base": "0,0"
}
}
```
scene.json:
```json
{
"owner": "0x8Bed95D830475691C10281f1FeA2c0a0fE51304B",
"scene": {
"parcels": ["-34,-130", "-35,-130"],
"base": "-34,-130"
}
}
```
scene.json:
```json
{
"scene": {
"parcels": ["0,0", "0,0"],
"base": "0,0"
}
}
```

fix: add parcels and ownership validations

---

linker-app/package.json
linker-app/src/components/Error.tsx
linker-app/src/components/Transaction.tsx
linker-app/src/components/TransactionStatus.tsx
linker-app/src/index.tsx
linker-app/src/modules/Ethereum.ts
linker-app/src/modules/Server.ts
linker-app/src/utils/coordinateHelpers.ts
src/lib/Decentraland.ts
src/lib/LinkerAPI.ts
typings/dcl.d.ts

Separate single `index.tsx` linked-app files into:

refactor: linker app separate from single file to multiple ones

---

linker-app/src/index.tsx
linker-app/src/modules/Ethereum.ts
linker-app/src/modules/Server.ts
src/lib/Ethereum.ts
src/lib/LinkerAPI.ts
src/lib/Project.ts

Added ownership check on Linker dApp

fix: web3 check ownership on linker-app

---

linker-app/src/index.tsx
linker-app/src/modules/Server.ts
src/lib/LinkerAPI.ts

With this a message is going to show up if `DCL_ENV` envrioment variable is turned on 'dev'

 feat: show test message if in development mode

---

src/commands/init.ts
src/lib/Project.ts
src/utils/filesystem.ts

feat: warning on dcl init if directory isn't empty

---

package-lock.json
package.json
src/lib/Preview.ts

feat: add rendezvous server

---

README.md
package-lock.json
package.json
src/commands/preview.ts
src/lib/Decentraland.ts
src/lib/Preview.ts
src/lib/Project.ts
src/samples/basic-static/package.json
src/samples/ts-dynamic/package.json
src/samples/ts-dynamic/scene.tsx
src/samples/ts-static/package.json
src/samples/ts-static/scene.tsx
src/samples/websockets/package.json
src/samples/websockets/server/RemoteScene.tsx
src/samples/websockets/server/Server.ts
src/samples/websockets/server/index.ts
src/samples/websockets/server/package.json
src/utils/moduleHelpers.ts
src/utils/wrapCommand.ts
test/integration/utils/moduleHelpers.spec.ts

Change the occurrences of metaverse-api for decentraland-api. Also, fix some flow control issues
Copyright claims

feat: rebrand metaverse-api -> decentraland-api

---

package-lock.json
package.json

fix: move ws from dev to dependencies

---

linker-app/src/components/LinkerPage/LinkerPage.container.tsx
linker-app/src/components/LinkerPage/LinkerPage.tsx

feat: add map of decentraland base parcel on deploy

---

linker-app/src/components/LinkerPage/LinkerPage.tsx
package-lock.json

feat: new UI for showing deploy metadata

---

src/commands/info.ts
src/commands/preview.ts
src/commands/status.ts
src/utils/analytics.ts
src/utils/moduleHelpers.ts
src/utils/wrapCommand.ts
test/integration/utils/moduleHelpers.spec.ts

We need to:
Track info command
Track status command
Track node version
Track decentraland-api version
Track cli version

chore: updated analytics

---

src/utils/coordinateHelpers.ts
test/unit/utils/coordinateHelpers.spec.ts

refer to: https://github.com/decentraland/marketplace/pull/387

fix: unconnected estates

---

abi/EstateRegistry.json
abi/MANAToken.json
linker-app/src/components/LinkerPage/LinkerPage.container.tsx
linker-app/src/components/LinkerPage/LinkerPage.tsx
linker-app/src/components/LinkerPage/types.ts
linker-app/src/contracts.ts
linker-app/src/modules/config.ts
linker-app/src/modules/land/actions.ts
linker-app/src/modules/land/sagas.ts
linker-app/src/modules/land/types.ts
linker-app/src/sagas.ts
package-lock.json
package.json
src/commands/deploy.ts
src/lib/Decentraland.ts
src/lib/Ethereum.ts
src/lib/LinkerAPI.ts
src/lib/Project.ts
src/utils/coordinateHelpers.ts
test/unit/lib/decentraland.spec.ts
typings/dcl.d.ts

Make CLI support `estateId` on `scene.json` and support deployments
We can now have a composable NFT called estate that owns a bounch of LAND.

feat: support estates development and deployment

---

package-lock.json
src/commands/info.ts
src/lib/Decentraland.ts
src/lib/Ethereum.ts
src/lib/Project.ts
src/utils/coordinateHelpers.ts

`dcl info [estateId]` same as `dcl info [parcel.x],[parcel.y]` but for estates.

feat: dcl info [estateId]

---

.circleci/config.yml
package-lock.json
package.json
src/lib/Preview.ts

Better with: https://github.com/decentraland/client/pull/399

fix: file mappings in preview

---

src/lib/Ethereum.ts
src/lib/Preview.ts

fix: windows paths in content mappings

---

src/lib/Ethereum.ts
src/lib/content/ContentUploadRequest.ts
test/unit/lib/content/contentuploadrequest.spec.ts

Send the request to the content service
...
To avoid using the cid as an identifier within the request
...

Change upload request

---

src/commands/info.ts

feat: show message for dissolved estates

---

src/samples/ecs/src/game.ts

Fix ecs example with latest changes
sample is not valid with latest changes

fix: update ecs sample

---

src/commands/deploy.ts
src/lib/Decentraland.ts
src/lib/content/ContentClient.ts
src/lib/content/ContentService.ts
src/lib/content/ContentUploadRequest.ts
test/unit/lib/content/contentservice.spec.ts
test/unit/lib/content/contentuploadrequest.spec.ts

Deploy the only missing content in the content server (unless the full deploy is forced)
Avoid deploying the same content over and over again

Allow partial deploy

---

src/commands/start.ts

fix: hotreloading on file changes

---

src/commands/deploy.ts
src/commands/info.ts
src/commands/status.ts

Change Content Server default url

---

LICENSE
README.md

Legal stuff

---

src/commands/deploy.ts
src/index.ts
src/lib/Decentraland.ts
src/lib/content/ContentClient.ts
src/utils/analytics.ts
src/utils/logging.ts

Related #304 
Prompt a Yes/No message if the scene to deploy is overlaping an existing one
Warn the developer

feat: prompt y/n question on scene overlap

---

samples/ecs/tsconfig.json

It only works if we allowJs true

fix: support eth-connect

---

src/lib/Decentraland.ts

fix: do not throw error on no previous Scene to validate

---

src/commands/deploy.ts
src/index.ts

fix: ensure that the process exit after command

---

src/commands/info.ts
src/commands/status.ts
src/utils/land.ts

fix: dcl status with negative first coord

---

src/utils/moduleHelpers.ts

fix: npm install

---

samples/ecs/package.json

feat: change the now boilerplate command to use dcl export

---

samples/ecs/src/game.ts

feat: change boilerplate to use .add instead of .set

---

package-lock.json
package.json
src/commands/deploy.ts
src/commands/export.ts
src/utils/buildProject.ts
src/utils/isECSProject.ts
src/utils/spinner.ts
test/e2e/export.test.ts
test/helpers/buildProject.ts

 feat: suggest building on deploy/export fail because of missing script

---

src/lib/Preview.ts

https://github.com/decentraland/explorer/pull/110

feat: serve unity build via express

---

package-lock.json
src/commands/init.ts
src/commands/start.ts
src/project/installDependencies.ts
src/project/isECSInstalled.ts
src/utils/moduleHelpers.ts
src/utils/spinner.ts

fix: only build dependencies on missing ECS and better DX feedback

---

src/commands/start.ts

`Cheking` -> `Checking`
Fixes a small spelling error in EN
I remembered this last night at like 3AM

chore: correct spelling in start.ts

---

src/commands/status.ts

fix: dcl status typo

---

src/lib/Preview.ts

Otherwise all messages come from peer "0".

fix: setAlias on server

---

src/lib/API.ts
src/lib/Decentraland.ts
src/lib/Ethereum.ts
src/lib/IEthereumDataProvider.ts

feat: show operators at

---

linker-app/src/components/LinkerPage/LinkerPage.tsx
linker-app/src/config.ts
src/lib/LinkerAPI.ts

feat: show friendly message on deploy error

---

src/utils/analytics.ts

fix: stop prompting analytics question

---

package-lock.json
package.json

Upgrade catalyst client version to prevent "too long url error"

Prevent too long url error

---

package-lock.json
package.json
src/lib/Preview.ts
src/lib/Project.ts
src/walletConnect/crypto.ts
webpack.config.js

* Prepare the ground for the new debugger functionalities.
* Fixes comms errors after every update
Once the PR is merged and the explorer#1404 also is, the way to access the new debugger is by adding `?WS_SCENE=1`to the preview URL.
Important: This is an opt-in feature. This is NOT the default behavior.
Level up in the maturity of the development cycle 🚀

feat: enable debugging in vscode

---

package-lock.json
package.json

Update client version

---

README.md

Update readme file to provide some extra information for users that may end up here
General description was missing

Update readme file to provide some extra information

---

package.json

Release new setupProxy configuration
...

chore: increase version to 3.7.0

---

src/lib/Preview.ts

chore: add cwd to update message

---

src/commands/deploy.ts

...
https://github.com/decentraland/sdk/issues/47

chore: add deploy scene success and deploy invoked analytics

---

package.json

release https://github.com/decentraland/cli/pull/581
...

chore: update package version to 3.8.1

---

src/commands/deploy.ts

Add try-catch statement to  build deploy and continue with deployment even if it fails. If there is no built, the deployment will fail.
To patch error-warning cases, when warnings error block the deploy even if build is done.

feat: handle error in build step.

---

src/commands/deploy.ts
test/e2e/export.test.ts

Add --skip-build param to deploy command.
https://github.com/decentraland/sdk/issues/58

feat: add skip build param deploy

---

package-lock.json
package.json

Upate linker-dapp version
...
...

update linkder-dapp version

---

package-lock.json
package.json
src/commands/deploy.ts

Update linker-dapp to 0.1.3
...
Now we receive the chainId instead of the network 
...

update linker-dapp version to 0.1.3

---

package-lock.json
src/index.ts

fix bin entrypoint

---

package-lock.json
package.json

add chalk missing dependency

---

.github/workflows/ci.yml
package-lock.json

update ci npm install command

---

src/lib/Preview.ts

feat: add payload to update message sceneType and sceneId

---

.eslintrc.json
.gitattributes
.github/workflows/ci.yml
src/commands/pack.ts
src/lib/Preview.ts

add lint to the ci

---

.github/workflows/ci.yml
package-lock.json

chore: change publish requirement

---

.github/workflows/dependabot.yml

add dependabot config for dcl packages

---

src/utils/analytics.ts

...
https://github.com/decentraland/sdk/issues/134

chore: add isCI to analytics anon id creation and track events function.

---

src/commands/deploy.ts
src/utils/moduleHelpers.ts

Closes https://github.com/decentraland/sdk/issues/193
...
...

return code 1 when the deploy fails

---

samples/library/npmrc
samples/portable-experience/npmrc
samples/scene/npmrc
src/lib/Project.ts
src/project/installDependencies.ts
src/utils/project.ts

fix npmrc files

---

samples/portable-experience/eslintrc.json
samples/portable-experience/package.json
samples/portable-experience/src/game.ts
samples/remote-scenes.json
samples/scene/eslintrc.json
samples/scene/package.json
samples/scene/src/game.ts
src/commands/init.ts
src/lib/Project.ts
src/utils/project.ts
src/utils/shellCommands.ts
test/e2e/init.test.ts

feat: extend `scene` option in `dcl init` to choose templates from examples scenes

---

src/commands/build.ts
src/commands/deploy.ts
src/commands/export.ts
src/commands/start.ts
src/utils/moduleHelpers.ts

...
https://github.com/decentraland/sdk/issues/233

feat: add warning message and check ecs && enable web 3 combination

---

samples/library/README.md

add library readme link

---

src/commands/deploy.ts

fix: add max file size limit

---

src/main.ts
src/utils/analytics.ts

fix unhandle promise

---

src/main.ts

fix segment filter error

---

src/commands/deploy.ts
src/commands/start.ts

fix catch error

---

package-lock.json
package.json
src/commands/deploy.ts
src/lib/LinkerAPI.ts
src/lib/Project.ts
src/utils/catalystPointers.ts
test/integration/Project.test.ts
test/unit/lib/Project.test.ts

https://github.com/decentraland/linker-dapp/pull/9
https://github.com/decentraland/opscli/pull/156
...
...

refactor linker-dapp

---

src/commands/deploy.ts
src/lib/LinkerAPI.ts

remove queryparams from deploy url to avoid spamming the console

---

package-lock.json
package.json
src/project/projectInfo.ts

fix: fix @dcl/schema version

---

src/utils/catalystPointers.ts

fix: deprecated endpoint

---

src/commands/build.ts
src/commands/deploy.ts
src/commands/start.ts
src/lib/Decentraland.ts
src/lib/Project.ts
src/main.ts
src/utils/analytics.ts

feat: add analytics event and data

---

package-lock.json
package.json

Update linker dapp to the next version
It fixes all permissions shown as granted

fix: update linker dapp version

---

package.json
src/lib/controllers/ecs6-endpoints.ts
src/lib/controllers/legacy-comms-v1.ts
src/project/projectInfo.ts

- Add the 'lambda/profiles' proxy to add preview wearables as equipped wearables.
- Fix the baseUrl and the URL made with hashes.
- also fix hot-reload in smart wearable preview (not working at latest CLI version)

review: rfc5 pr review

---

src/lib/controllers/ecs6-endpoints.ts

fix ecs7 start error

---

package-lock.json
src/utils/analytics.ts

feat: add editor analytics var

---

package-lock.json
src/commands/start.ts

feat: remove branches sdk7

---

package.json
src/commands/start.ts
src/lib/Project.ts

fix: `dcl start` without dependencies fails

---

src/commands/start.ts
src/lib/controllers/ecs6-endpoints.ts

chore: move on to use @dcl/explorer as first option

---

package-lock.json
package.json
src/commands/deploy.ts
src/commands/start.ts
src/lib/Preview.ts
src/lib/Project.ts
src/lib/controllers/bff.ts

SDK 6 new release

---

src/commands/init/utils.ts
test/e2e/init.test.ts

remove smart items and smart wearable options for sdk6
