decentraland/cli

README.md, src/commands/init.ts, src/commands/update.ts, src/utils/linker.ts, src/utils/serve.ts, src/utils/uploader.ts
Fix #39 #36
`dcl init` now creates DCL project **inside of working directory**!
1. `npm run build`
2. `npm start -- init`
3. every other command should now look for `tmp` directory and don't ask for any additional questions in console.
After `npm link`:
1. `mkdir project-name`
2. `cd project-name`
3. `dcl init`
4. every other command should now look for `'.'` directory.
=> use `dcl init` and other commands from working dir, refactor dev mode

README.md, live-reload.js, package.json, src/commands/init.ts, src/utils/generate-html.ts
Fixes #35 and #42, I also added a `watch` script that we can run after the first `npm run build` to do incremental compilations (it doesn't rebuild the linker tho, for that one we need to re-run `npm run build` after we make changes to it).
=> fix client url, live-reload, and added watch script

package.json, pages/linker.js, src/commands/init.ts, src/utils/linker.ts, src/utils/uploader.ts
This PR solves the bug that is preventing two projects to have different IPNS links. The problem was that the IPFS key used to generate the IPNS hash was the Peer ID (one per IPFS node), so all the projects using the same IPFS daemon would end up having the same IPNS link.
I added a `project.json` in `.decentraland` that cointains a unique id for the project, and the IPFS key's **name** (note that this is only a reference to the private key, the actual private key is stored in the ipfs node. This hash is actually what ends up being the ipns hash in the end, so it can be public).
I tried to add `export` / `import` commands to be able to get the `.pem` and load it again (ie. from a different computer) but I ran into some weird IPFS exceptions, I'll leave that one for a second PR.
Currently …
=> [fix] IPNS links

README.md, package.json
- update dependencies with `npm update`
- add requirements and installation info to readme (with links)
- add minimum `node` version we support in `package.json` (8.0.0 and above supports everything we use from ES6)
Closes #58, #63, #67.
=> chore: upgrades and windows support

package.json
- `prepublish` to `prepublishOnly`
=> :twisted_rightwards_arrows: change to prepublishOnly based on  npm5 warning

src/utils/uploader.ts
- Fill `ipnsHash` with the result of `publish` (same as `project.ipfskey` --> we should consider naming it ipns)
- If it is an upload, track the event when pinning is finished
=> :bug: remove duplicate tracking at upload & set ipnsHash

package.json, pages/linker.js, src/postinstall.ts, src/preview/serve.ts, src/utils/analytics.ts
- `dcl start` now looks for a local `dcl-sdk` installed in the folder it is executing
- Fixes a couple of bugs
Testing strategy:
- Fetch this branch
- `npm run build`
- `npm link` (links the global `dcl` command to this folder)
- Create a new typescript project, install the latest SDK in that folder, use it with the `Component` feature and it should work
=> feat: allow any sdk version

package.json, src/lib/Project.ts, test/lib/project.spec.ts, tslint.json
Closes [CLIENT-41](https://decentraland.atlassian.net/browse/CLIENT-41)
A project now fails to init if there's an existing `.decentraland` folder or an existing `scene.json` file.
=> fix: validateNewProject

README.md, package-lock.json, package.json, src/commands/init.ts, src/index.ts, src/lib/Ethereum.ts, src/lib/IPFS.ts, src/utils/env.ts, typings/decentraland-commons.d.ts
Changes NODE_ENV usage to DCL_ENV for internal use. We want to free NODE_ENV for end users without changing to ropsten.
Closes [CLIENT-80](https://decentraland.atlassian.net/browse/CLIENT-80)
=> chore: changed NODE_ENV to DCL_ENV for internal use

src/utils/analytics.ts
If user disabled sending usage info, commands should work (Promise now resolves).
=> fix: resolve promise even when tracking disabled

src/commands/deploy.ts, src/lib/Project.ts, src/samples/basic-static/package.json, src/samples/basic-ts/package.json, src/samples/websockets/package.json, src/utils/errors.ts, test/integration/lib/project.spec.ts, test/unit/lib/project.spec.ts
- require .dclignore for deployments
- autogenerate it if missing
- preview should work without .dclignore
=> fix: require dclignore for deployments but not for preview

src/utils/analytics.ts
We should send analytics of this question regardless of the answer:
> Send anonymous usage stats to Decentraland?
=> fix: send answer of event (Send Anonymous data)

linker-app/src/modules/Server.ts
CLI is not able to deploy because IPFS key isn't being correctly parsed, this PR solves that.
=> fix: correctly parse IPFS key

src/commands/preview.ts, src/lib/Decentraland.ts, src/lib/Preview.ts
This feature allows to run `dcl start` on https://now.sh
=> feat: add "no-watch" functionality to preview

src/commands/preview.ts, src/samples/basic-static/package.json, src/samples/ts-dynamic/package.json, src/samples/ts-static/package.json, src/samples/websockets/package.json, src/utils/env.ts, src/utils/index.ts, src/utils/wrapCommand.ts
Implements #216 
Reads environment variables NOW (injected by now.sh) and CI (injected by most of CI services) and if they are set on true the CLI will continue on `--ci` mode regardless of the flag is set or not.
We want to be now-ready when making `dcl init` without extra steps such like modifying `npm start` script or running `npm install --save-dev decentraland` before deploying.
=> feat: support now and CIs by default

linker-app/src/modules/config.ts, linker-app/src/sagas.ts, src/lib/Ethereum.ts, src/lib/LinkerAPI.ts, src/utils/env.ts
We aren't having a single source of truth when we talk about contract addresses and providers, linker-app was using hardcoded infura same as CLI and some functions where fetching contract addresses from [contracts.decentraland.org/addresses.json](https://contracts.decentraland.org/addresses.json) but others have also hardcoded addresses
Avoid a properties mess, prior env variables, otherwise fetch missing ones.
=> refactor: let's have a single source of addresses and providers

src/commands/init.ts, test/e2e/cli/01.init.spec.ts, test/e2e/cli/02.deploy.spec.ts, typings/dcl.d.ts
Check that we're checking ownership of parcels on deploy
Because we are not asking setup questions anymore on init. We'll take `create-react-app` or `npm` approach and ask the less info as possible for init and start and all the things that need for deploying only at `dcl deploy`.
=> test: check ownership on deploy

src/utils/moduleHelpers.ts
Fetching ping endpoint instead of the entire landing
To avoid extra bandwidth consumption
=> Fixes #227

package-lock.json, src/samples/ecs/.vscode/settings.json, src/samples/ecs/src/game.ts
It fixes the example to use the latest version of the API and also adds a necessary configuration for VSCode to find the types
=> chore: update ECS example

linker-app/src/modules/land/sagas.ts, src/commands/deploy.ts, src/lib/Decentraland.ts, src/lib/content/ContentService.ts, test/unit/lib/decentraland.spec.ts
Makes CLI work again because we now retrieve the public address from chrome instead of node process to after that upload it to the content server
Because we don't want CLI users get mad 😡
=> fix: CLI not working because of decentraland-eth usage at Node.js

linker-app/src/components/LinkerPage/LinkerPage.container.tsx, linker-app/src/components/LinkerPage/LinkerPage.tsx, linker-app/src/components/LinkerPage/types.ts, linker-app/src/contracts.ts, linker-app/src/modules/config.ts, linker-app/src/modules/land/sagas.ts, linker-app/src/modules/land/utils.ts, linker-app/src/sagas.ts, package-lock.json, src/commands/info.ts, src/lib/Decentraland.ts, src/lib/LinkerAPI.ts, src/lib/Project.ts, test/unit/lib/decentraland.spec.ts
Remove estate deployment logic from the CLI and the Linker Dapp
Estates are only being used as a shorthand or business logic for LAND trading only, it does nothing to do with scenes.
=> chore: remove all estate deployment logic from project

src/lib/API.ts, src/lib/Decentraland.ts, src/lib/Ethereum.ts, src/utils/land.ts
Makes the `dcl info` command for parcels of estates show real owners instead of estate registry + an estate preview of the parcel
=> fix: make `dcl info` parcels of estates show real owners  

src/lib/content/ContentService.ts
There is a non-handled error when no-content LANDs are being deployed or requested via `dcl info`
The content service needs to handle this error and return null
=> fix: do not throw error on no-content LANDs

src/commands/deploy.ts, src/commands/info.ts, src/commands/info.ts.rej, src/index.ts
=> fix: `dcl info` for negative X coords

src/lib/Preview.ts
Closes #388 
Related/dependant: https://github.com/decentraland/client/pull/561
Pass as script variable the boolean of `node_modules/eth-connect` path exists to the client preview artifact 
So users don't have to handle the overhead of web3, having metamask installed or having to logging/signing if they don't need it
=> feat: preview - only prompt metamask on eth-connect scenes

src/lib/Preview.ts
This reverts commit 63fccfe984ecc4ca77c44a1820df870d6f03bdbc.
Moving Unity to be default preview
=> Revert "feat: serve both babylon and unity previews"

src/lib/Preview.ts
Fixes https://github.com/decentraland/cli/issues/433
=> fix: do not explode on `dcl start` when .dclignore is missing

src/lib/Preview.ts
Add a `/scenes` and `/parcel_info` endpoints according to the latest https://github.com/decentraland/content-service changes
So we can unblock https://github.com/decentraland/explorer/pull/224
Closes https://github.com/decentraland/cli/issues/440
=> feat: add mock scene endpoints

src/commands/deploy.ts
Removed at least until there is a specific definition or requirement for this limitation that is until now blocking some users.
=> fix: remove MAX_FILE_COUNT

src/lib/Project.ts
When deploying a scene, all files that are not on the `.dclignore` file are uploaded to the content server. The problem is that in many cases, unwanted files end up being uploaded. This generates problems during deployment (since there is a limit on the upload size), and could also end up with unwanted files on all content servers.
=> feat: including more files in .dclignore 

.gitignore, package-lock.json, package.json, postbuild.js, postinstall.js, src/lib/LinkerAPI.ts
Closes #508 
I moved `decentraland-ui` from `dependencies` to `devDependencies` so it doesn't get installed when installing the CLI. It still get's installed in for development, and I added a postinstall script that copies it's contents to the `src/css` directory where it is consumed by the `LinkerAPI.ts`. Finaly I added a `postbuild` that copies the files from `src/css` into `dist/css` so the CLI server can find them when installed from NPM.
To get rid of the peer dependecy warnings that show in the console when a users installs the CLI.
=> chore: make decentraland-ui a dev dependency

package-lock.json, package.json, src/commands/init.ts, src/sceneJson/types.ts
This PR is doing two things:
1. We are adding the `requiredPermissions` property to the default `scene.json` file, so people know it exists
1. We are upgrading the version of `dcl-catalyst-client`. This new version calculates the timestamp of the deployment with an external API, so if the user that is currently deploying has a wrong time on their local machine, the deployment will still succeed.
=> chore: add permissions to default scene json

package.json
This PR prevents the postinstall script to throw
The `postinstall` script is necessary for the development of the lib (see https://github.com/decentraland/cli/pull/509) but it's not necessary to run it when a user installs the lib using `npm install -g decentraland` since those files are already bundled by the `postbuild` script.
=> fix: skip post install when not necessary

package.json
Right now, when installing or updating the cli, an error is show:
```
internal/modules/cjs/loader.js:638
throw err;
^
Error: Cannot find module '/Users/nchamo/repos/cli/postintall'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
The cli is still installed/updated, but the error is shown, causing confusion
=> fix: avoid console error when installing the cli

src/commands/export.ts
During the last changes to the initial loading screen, the export page was not updated. Therefore, when exporting scenes, it wasn't possible to enable web3.
In order for it to work, we copied the current `preview.html`, and made a few little changes for it to be compatible with exporting scenes. Now, we need to copy the images that the preview displays.
=> fix: enable web3 when exporting scenes

src/commands/build.ts
Should always show the output of the build. I had a scene not working and it was because it had errors in the code I was not seeing.
Avoid headaches
=> fix: "dcl build" should always show the output of the build

src/commands/deploy.ts
Previously, we failed silently when a project didn't have a `tsconfig.json`. Now we show the error message
=> fix: show error when scene project doesn't have tsconfig.json

package.json
=> chore: releasing new version

src/lib/API.ts, src/lib/content/ContentService.ts
This is a continuation of https://github.com/decentraland/cli/pull/534, trying to solve remaining issues in https://github.com/decentraland/cli/issues/533
We are no supporting estates with more than 100 parcels, and stop failing when information about an empty parcel is required
=> fix: support estates with more than 100 parcels

package.json
We have fixed (and confirmed the fixes) all problems in https://github.com/decentraland/cli/issues/533, so we can now release a new version of the cli
=> chore: release 3.4.7

package-lock.json, package.json, src/commands/deploy.ts
We are currently getting the error `ReferenceError: Blob is not defined`
We are now using the new update in https://github.com/decentraland/catalyst-client/pull/72 to avoid such error
=> fix: avoid blob error

src/commands/export.ts
Support export with new version of SDK
run `dcl export` with an old version of the ecs `6.6.3` and with `@next`
Both cases should work properly
=> fix: support both new renderer and old versions of the SDK

package.json, src/utils/logging.ts
Fixes https://github.com/decentraland/cli/issues/533
**Context:**
`dcl info` can show information about a specific parcel. It prints on the console some information regarding the scene's metadata.
The problem was that a specific scene had a `0` set as a spawn point. So the code would not enter the `if (item)` part, and the accumulator in the reduce would be undefined (since there was no else). In the next iteration, it would fail
=> fix: avoid errors with 0 value

src/lib/Preview.ts
It adds support for a proxy which it's loaded from the ECS module if it exists (specifically from node_modules/decentraland-ecs/src/setupProxy.js)
See more https://github.com/decentraland/sdk/issues/12
=> feat: load setupProxy.js in preview

src/commands/export.ts
Find a setupExport.js file in the decentraland-ecs package, if it exists, it's called it instead of standard export.
In accordance with the new package structure, this allows setting up a custom package export from the ECS. Also, it's maintaining compatibility with the current structure.
1. Build and link the CLI `npm run build && npm link`
2. In a scene project, run `dcl export` and check if it works properly
3. Remove the export generated and create a file in `node_modules/decentraland-ecs/src/setupExport.js` with `module.exports = function (exportDir, sceneTitle, mappings){
console.log("Hello world");
}`
4. Run again `dcl export` and note only project files were copied without any package
=> feat: import setupExport from decentraland-ecs and call it if exists

src/commands/build.ts, src/commands/deploy.ts, src/commands/export.ts, src/commands/start.ts, src/utils/moduleHelpers.ts
Add a minimum version matcher between CLI and ECS. 
https://github.com/decentraland/sdk/issues/39
1. Build and link this CLI branch
2. Create a folder and run `dcl init` there.
3. Modify $SCENE_FOLDER/node_modules/decentraland-ecs/package.json and $CLI_FOLDER/package.json with the requirements to test
=> feat: add checks on dcl start/deploy/build/export

src/utils/installedDependencies.ts
Closes https://github.com/decentraland/sdk/issues/85
Log error instead of failing
...
When there is an unmet peer dependencies `dcl start` and `dcl install` fail to update package.json with the updated bundleDepencies.
This is beacuse `npm ls --json` exits with a code 1.
...
=> handle peer dependencies unmet as a warning

src/commands/start.ts
Now list the network interfaces and prioritize localhost at first (to open browser) (cors)
The feature was missed in the workspace PR
https://github.com/decentraland/cli/commit/c09427be2142f003036baacb3ca175e873efda92#diff-fad98b12cdbc949be417ed9f456c26c2c5066dc9351e0f79506a9cd3900351e1L151
Can be related to https://github.com/decentraland/cli/issues/648
=> fix: list network interfaces

.gitignore, package-lock.json, package.json
Upgrade `@dcl/linkder-dapp` to get support for WalletConnect, WalletLink and Fortmatic.
=> feat: upgrade linker dapp

src/lib/controllers/ecs6-endpoints.ts
To don't have a fixed catalyst on ECS6. Now you can configure your preferent catalyst.
=> feat: catalystUrl from .dclinfo

package-lock.json, package.json
This PR upgrades the linker-dapp to the version `v0.6.0` which includes:
-  The fix for the issue were rented land could not be deployed onto
- The NPS survey after a successful deployment (see https://github.com/decentraland/sdk/issues/543)
=> chore: upgrade linker-dapp

src/lib/controllers/ecs6-endpoints.ts
fix: while creating a smart-wearable project, the portable experience is being not added to the portable experiences menu
=> fix: smart wearables

src/utils/moduleHelpers.ts
For the SDK7 we dont use anymore the CLI. So if you want to use an outdated version like 7.0.5 this will always fail.
=> remove latest condition for sdk7

src/commands/deploy.ts, src/lib/Project.ts
This PR adds --skip-file-size-check to dcl deploy which ignores the 50 MB file size check when deploying to a worlds server using --target-content
The deployer should be able to relax this constraint when deploying to a private worlds server. Scenes with file sizes larger than 50 MB function locally when developing, and should be able to be deployed.
closes #785
=> Adds skip file size check

src/config.ts
use mainnet as default network
...
When you use the ci param in the start command `dcl start --ci` and you try to use ENABLE_WEB3 to use your profile, then the fetch was being done to the .zone because the network was undefined.
https://github.com/decentraland/cli/blob/main/src/main.ts#L80-L94
...
=> fix network when ci param is set

src/config.ts
This PR replaces the land manager subgraph link with a new one that targets our own subgraph worker. This worker will handle requests for all subgraphs redirecting to TheGraph studio or satsuma depending on availability
TheGraph hosted service reaches EOL
=> feat: update land manager subgraph link
